Sprint 2/step 2
itsanti/react-burger pull request #4
Opened 2024-02-10 09:30 UTC by itsanti

2024-02-10 11:10 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть небольшое замечание, которое нужно исправить:**

- <https://disk.yandex.com/i/PcZ5SIZSM5PQIQ> - Нужно чуток подправить верстку, в соответствии с дизайном - <https://disk.yandex.com/i/PcZ5SIZSM5PQIQ>. Показал стрелками на втором скрине, на что стоит обратить внимание;

### **Замечания "Можно лучше:" не обязательны к исправлению.**

2024-02-10 11:10 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor-element/burger-constructor-element.js
> +        }}
**Можно лучше:**

Обработчик события лучше вынести в отдельную функцию. Здесь и в похожих местах.

2024-02-10 11:10 UTC, ArslanMustafin commented on src/index.js
> +    {/*<React.StrictMode>*/}
**Можно лучше:**

рекомендую оставлять `strict-mode` он помогает выявлять ошибки на различных слоях приложения.
Подробнее тут - https://react.dev/reference/react/StrictMode;

2024-02-10 11:10 UTC, ArslanMustafin commented on src/services/selectors/burgconstructor.js
> +};
**Можно лучше:**

если вы что-то вычисляете в селекторах, то лучше для этого использовать reselect - https://reselect.js.org.

2024-02-10 17:30 UTC, itsanti commented
@ArslanMustafin привет.

- ссылка на оба скрина одинаковая
- у меня на хромиум браузерах вёрстка скролла такая. если это сафари, то мне не проверить даже. что нужно исправить. 
![image](https://github.com/itsanti/react-burger/assets/1463274/6148fd2b-041c-43e2-a465-be82b6d5cb75)

2024-02-10 19:10 UTC, ArslanMustafin commented
> @ArslanMustafin привет.
> 
> * ссылка на оба скрина одинаковая
> * у меня на хромиум браузерах вёрстка скролла такая. если это сафари, то мне не проверить даже. что нужно исправить.
>   ![image](https://private-user-images.githubusercontent.com/1463274/303855041-6148fd2b-041c-43e2-a465-be82b6d5cb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1OTIyNjksIm5iZiI6MTcwNzU5MTk2OSwicGF0aCI6Ii8xNDYzMjc0LzMwMzg1NTA0MS02MTQ4ZmQyYi0wNDFjLTQzZTItYTQ2NS1iZTgyYjZkNWNiNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTkwNjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZlYTc4ZGRmYzgyNmZiZjY4YzBiYjU1NWQwZDQ4ZTk1OTQzZTI0NTNmMmU3MTYxOGVmMzMxMWYzYjIxMzEwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i1lcrd84PghHGnSNfg7XDL3sUZVdlMXryqFzzxXnG30)

Привет, сорри что скрин не тот, на винде Я.Диск сразу ссылку выдаёт, а на mac почему задержка, поэтому и бывают такие случаи)) 

https://disk.yandex.com/i/ZVu1dhsEoLjnCQ 

Я проверяю всегда в хроме, и скролл у других студентов норм)) Попробуй вот такие стили в index.css вставить, который в корне.

```js
::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
  background: #2f2f37;
}

::-webkit-scrollbar-thumb {
  border: 3px solid #8585ad;
  background: #8585ad;
}
```

2024-02-10 20:10 UTC, itsanti commented
@ArslanMustafin попробовал разные варианты под скролл. похоже хром его сломал недавно - [был тред на SO](https://stackoverflow.com/questions/77894066/webkit-scrollbar-design-is-not-working-in-chrome-version-121-0-6167-86).

2024-02-11 11:23 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-02-11 11:45 UTC, merged